name: Deploy to GitHub pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  QUARTO_VERSION: "1.1.189"
  R_VERSION: "4.2"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: sudo apt-get install -y libglpk-dev

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: ${{ env.QUARTO_VERSION }}

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ env.R_VERSION }}

      - name: Install R dependencies
        uses: r-lib/actions/setup-renv@v2

      - name: Run targets pipeline
        run: targets::tar_make()
        shell: Rscript {0}

      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: gh-pages/_site/
